plugins:
  eslint:
    channel: eslint-6
    config:
      config: .eslintrc.json
      extensions:
        - .mjs
        - .ts
      ignore_warnings: true
    enabled: true
exclude_patterns:
  - "**/*.cjs"
  - "**/*.js"
